/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["post_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Examples */
        get: operations["get_lab_examples_api_lab_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/examples/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Example */
        get: operations["get_lab_example_api_lab_examples__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Job */
        get: operations["get_lab_job_api_lab_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lab Options */
        get: operations["get_lab_options_api_lab_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/pathways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Lab Pathways */
        post: operations["post_lab_pathways_api_lab_pathways_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Lab Replay */
        post: operations["post_lab_replay_api_lab_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Lab Report */
        post: operations["post_lab_report_api_lab_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lab/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Lab Run */
        post: operations["post_lab_run_api_lab_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/neurons/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Neuron Search */
        get: operations["get_neuron_search_api_neurons_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/neurons/{cell_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Neurons */
        get: operations["get_neurons_api_neurons__cell_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenarios */
        get: operations["get_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stimulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Stimulate */
        post: operations["post_stimulate_api_stimulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Behavior
         * @enum {string}
         */
        Behavior: "feeding" | "escape" | "antennal_grooming" | "backward_walking" | "forward_walking";
        /** BehaviorComparison */
        BehaviorComparison: {
            behavior: components["schemas"]["Behavior"];
            /** Control Rate Hz */
            control_rate_hz: number;
            /** Difference Hz */
            difference_hz: number;
            /** P Value */
            p_value: number;
            /** Percent Change */
            percent_change: number | null;
            /** Significant */
            significant: boolean;
            /** Silenced Rate Hz */
            silenced_rate_hz: number;
        };
        /** BehaviorDifference */
        BehaviorDifference: {
            behavior: components["schemas"]["Behavior"];
            /** Condition */
            condition: string;
            /** Replayed Rate Hz */
            replayed_rate_hz: number;
            /** Reported Rate Hz */
            reported_rate_hz: number;
        };
        /** BehaviorReadout */
        BehaviorReadout: {
            /** Active */
            active: boolean;
            behavior: components["schemas"]["Behavior"];
            /** Rate Hz */
            rate_hz: number;
            /** Rate Std Hz */
            rate_std_hz: number;
            /** Readout Group */
            readout_group: string;
            /** Score */
            score?: number | null;
        };
        /** BrainActivity */
        BrainActivity: {
            /** Neuropil Rates Hz */
            neuropil_rates_hz: {
                [key: string]: number;
            };
            /**
             * @default {
             *       "max_hz": 200,
             *       "reference_hz": 0.5
             *     }
             */
            scale: components["schemas"]["BrainScale"];
        };
        /**
         * BrainScale
         * @description Beyin şeması parlaklık ölçeği (tüm senaryolarda sabit):
         *
         *     parlaklık = log10(1 + hız / reference_hz) / log10(1 + max_hz / reference_hz), [0, 1]'e kırpılır.
         */
        BrainScale: {
            /**
             * Max Hz
             * @default 200
             */
            max_hz: number;
            /**
             * Reference Hz
             * @default 0.5
             */
            reference_hz: number;
        };
        /** CellTypeMatch */
        CellTypeMatch: {
            /** Cell Type */
            cell_type: string;
            /** Neuron Count */
            neuron_count: number;
        };
        /** CellTypeResponse */
        CellTypeResponse: {
            /** Cell Type */
            cell_type: string;
            /** In Model Count */
            in_model_count: number;
            /** Neuron Count */
            neuron_count: number;
            /** Neurons */
            neurons: components["schemas"]["NeuronInfo"][];
        };
        /** CellTypeSelector */
        CellTypeSelector: {
            /** Cell Type */
            cell_type: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "cell_type";
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /** ChatResponse */
        ChatResponse: {
            brain: components["schemas"]["BrainActivity"];
            classification: components["schemas"]["ClassificationInfo"];
            hint: components["schemas"]["OutOfScopeHint"] | null;
            output: components["schemas"]["DecoderOutput"];
            presentation: components["schemas"]["PresentationInfo"];
        };
        /** ClassificationInfo */
        ClassificationInfo: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** In Scope */
            in_scope: boolean;
            /** Levels */
            levels: {
                [key: string]: number;
            };
            /** Out Of Scope Reason */
            out_of_scope_reason: string | null;
        };
        /** ConditionResult */
        ConditionResult: {
            /** Label Tr */
            label_tr: string;
            /** Neuropil Rates Hz */
            neuropil_rates_hz: {
                [key: string]: number;
            };
            output: components["schemas"]["DecoderOutput"];
        };
        /** DecoderOutput */
        DecoderOutput: {
            /** Active Neuron Count */
            active_neuron_count: number;
            /** Behaviors */
            behaviors: components["schemas"]["BehaviorReadout"][];
            /** Circuit Only */
            circuit_only: boolean;
            model: components["schemas"]["ModelInfo"];
            stimulus: components["schemas"]["StimulusInfo"];
            /** Top Neuropils */
            top_neuropils: components["schemas"]["NeuropilActivity"][];
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Category */
            category: string;
            /** Clause */
            clause: string;
            /** Rule */
            rule: string;
            /** Term */
            term: string;
        };
        /** ExampleInfo */
        ExampleInfo: {
            /** Name */
            name: string;
            /** Title Tr */
            title_tr: string;
        };
        /** ExperimentReport */
        ExperimentReport: {
            /** Created Utc */
            created_utc: string;
            provenance: components["schemas"]["Provenance"];
            /**
             * Report Version
             * @default 1
             */
            report_version: number;
            request: components["schemas"]["ExperimentRequest"];
            result: components["schemas"]["ExperimentResult"];
            /**
             * Title Tr
             * @default Laboratuvar deneyi
             */
            title_tr: string;
        };
        /** ExperimentRequest */
        ExperimentRequest: {
            /**
             * @default {
             *       "n_trials": 30,
             *       "seed": 0,
             *       "t_run_ms": 1000
             *     }
             */
            params: components["schemas"]["LabParams"];
            /** Silenced */
            silenced?: (components["schemas"]["GroupSelector"] | components["schemas"]["CellTypeSelector"] | components["schemas"]["TransmitterSelector"] | components["schemas"]["NeuropilSelector"] | components["schemas"]["IdsSelector"])[];
            /** Stimuli */
            stimuli: components["schemas"]["LabStimulus"][];
        };
        /** ExperimentResult */
        ExperimentResult: {
            /** Comparisons */
            comparisons: components["schemas"]["BehaviorComparison"][];
            control: components["schemas"]["ConditionResult"];
            /** Duration Seconds */
            duration_seconds: number;
            params: components["schemas"]["LabParams"];
            /** Silenced */
            silenced: components["schemas"]["Selection"][];
            silenced_condition: components["schemas"]["ConditionResult"] | null;
            /** Silenced Neuron Count */
            silenced_neuron_count: number;
            /** Stimuli */
            stimuli: components["schemas"]["Selection"][];
            /** Stimulus Rates Hz */
            stimulus_rates_hz: number[];
            /** Warnings Tr */
            warnings_tr: string[];
        };
        /** GroupSelector */
        GroupSelector: {
            /** Group */
            group: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "group";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Llm Enabled */
            llm_enabled: boolean;
            llm_provider: components["schemas"]["LLMProvider"];
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** IdsSelector */
        IdsSelector: {
            /** Ids */
            ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ids";
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "queued" | "running" | "done" | "error";
        /**
         * JobStatus
         * @description Arka planda çalışan Laboratuvar işi. Sonuç, işin türüne göre ilgili alanda döner.
         */
        JobStatus: {
            /** Error Tr */
            error_tr?: string | null;
            experiment?: components["schemas"]["ExperimentResult"] | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "run" | "pathways" | "report" | "replay";
            pathways?: components["schemas"]["PathwayResponse"] | null;
            /** Progress */
            progress: number;
            replay?: components["schemas"]["ReplayResult"] | null;
            report?: components["schemas"]["ExperimentReport"] | null;
            state: components["schemas"]["JobState"];
            /** Step Tr */
            step_tr: string;
        };
        /**
         * LLMProvider
         * @description Sunum katmanında kullanılabilecek LLM sağlayıcıları.
         * @enum {string}
         */
        LLMProvider: "none" | "gemini" | "groq" | "ollama";
        /** LabGroupInfo */
        LabGroupInfo: {
            behavior: components["schemas"]["Behavior"] | null;
            /** Key */
            key: string;
            /** Name Tr */
            name_tr: string;
            /** Neuron Count */
            neuron_count: number;
            /** Role */
            role: string;
        };
        /** LabOptions */
        LabOptions: {
            /** Busy */
            busy: boolean;
            /** Groups */
            groups: components["schemas"]["LabGroupInfo"][];
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Neuropils */
            neuropils: string[];
            /** Neurotransmitters */
            neurotransmitters: string[];
        };
        /** LabParams */
        LabParams: {
            /**
             * N Trials
             * @default 30
             */
            n_trials: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * T Run Ms
             * @default 1000
             */
            t_run_ms: number;
        };
        /** LabStimulus */
        LabStimulus: {
            /** Rate Hz */
            rate_hz: number;
            /** Selector */
            selector: components["schemas"]["GroupSelector"] | components["schemas"]["CellTypeSelector"] | components["schemas"]["TransmitterSelector"] | components["schemas"]["NeuropilSelector"] | components["schemas"]["IdsSelector"];
        };
        /** ModelInfo */
        ModelInfo: {
            /**
             * Dataset
             * @default FlyWire v783
             * @constant
             */
            dataset: "FlyWire v783";
            mode: components["schemas"]["SimulationMode"];
            /** N Trials */
            n_trials: number;
            /** Package Version */
            package_version?: string | null;
            /** Seed */
            seed: number;
            /**
             * Sign Source
             * @default reference
             * @enum {string}
             */
            sign_source: "reference" | "annotations";
            /** T Run Ms */
            t_run_ms: number;
            /**
             * Type
             * @default LIF
             * @constant
             */
            type: "LIF";
        };
        /** NeuronInfo */
        NeuronInfo: {
            /** Cell Class */
            cell_class: string | null;
            /** Groups */
            groups: string[];
            /** In Model */
            in_model: boolean;
            /** Root Id */
            root_id: string;
            /** Side */
            side: string | null;
            /** Super Class */
            super_class: string | null;
            /** Top Nt */
            top_nt: string | null;
            /** Top Nt Conf */
            top_nt_conf: number | null;
        };
        /** NeuropilActivity */
        NeuropilActivity: {
            /** Events Hz */
            events_hz: number;
            /** Neuropil */
            neuropil: string;
            /** Share */
            share: number;
        };
        /** NeuropilSelector */
        NeuropilSelector: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "neuropil";
            /** Neuropil */
            neuropil: string;
        };
        /** OutOfScopeHint */
        OutOfScopeHint: {
            /** Examples */
            examples: string[];
            /** Title */
            title: string;
        };
        /** PackageInfo */
        PackageInfo: {
            /** Available */
            available: boolean;
            /** Problem */
            problem: string | null;
            /** Version */
            version: string | null;
        };
        /** PathEdge */
        PathEdge: {
            /** Excitatory */
            excitatory: boolean;
            /** Post Cell Type */
            post_cell_type?: string | null;
            /** Post Id */
            post_id: string;
            /** Pre Cell Type */
            pre_cell_type?: string | null;
            /** Pre Id */
            pre_id: string;
            /** Pre Rate Hz */
            pre_rate_hz: number;
            /** Share */
            share: number;
            /** Synapses */
            synapses: number;
        };
        /** Pathway */
        Pathway: {
            /** Edges */
            edges: components["schemas"]["PathEdge"][];
            /** Excitatory */
            excitatory: boolean;
            /** Hops */
            hops: number;
            /** Strength */
            strength: number;
        };
        /** PathwayRequest */
        PathwayRequest: {
            behavior: components["schemas"]["Behavior"];
            experiment: components["schemas"]["ExperimentRequest"];
            /**
             * Max Hops
             * @default 4
             */
            max_hops: number;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** PathwayResponse */
        PathwayResponse: {
            /** Note Tr */
            note_tr: string;
            /** Pathways */
            pathways: components["schemas"]["Pathway"][];
            /** Target Id */
            target_id: string;
        };
        /** PresentationInfo */
        PresentationInfo: {
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Model */
            model: string | null;
            /** Provider */
            provider: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "llm" | "template";
            /** Text */
            text: string;
        };
        /** Provenance */
        Provenance: {
            /** Calibration Sha256 */
            calibration_sha256: string;
            /**
             * Dataset
             * @default FlyWire v783
             */
            dataset: string;
            /** Environment */
            environment: {
                [key: string]: string;
            };
            /** Neuron Groups Definitions Sha256 */
            neuron_groups_definitions_sha256: string;
            /**
             * Sign Source
             * @default reference
             */
            sign_source: string;
            /** Sinek Version */
            sinek_version: string;
            /** Sources Sha256 */
            sources_sha256: {
                [key: string]: string;
            };
        };
        /** ReplayResult */
        ReplayResult: {
            /** Differences */
            differences: components["schemas"]["BehaviorDifference"][];
            /** Identical */
            identical: boolean;
            /** Max Difference Hz */
            max_difference_hz: number;
            /** Provenance Matches */
            provenance_matches: boolean;
            /** Provenance Notes */
            provenance_notes: string[];
            result: components["schemas"]["ExperimentResult"];
        };
        /** ReportRequest */
        ReportRequest: {
            experiment: components["schemas"]["ExperimentRequest"];
            /** Title Tr */
            title_tr?: string | null;
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Components */
            components: [
                string,
                number
            ][];
            /** Key */
            key: string;
            /** Precomputed */
            precomputed: boolean;
        };
        /** ScenariosResponse */
        ScenariosResponse: {
            /** Groups */
            groups: components["schemas"]["StimulusGroupInfo"][];
            package: components["schemas"]["PackageInfo"];
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioInfo"][];
        };
        /**
         * Selection
         * @description Çözümlenmiş seçim: kullanıcıya gösterilen tanım + tekrar üretilebilir kimlik listesi.
         */
        Selection: {
            /** Flywire Ids */
            flywire_ids: string[];
            /** Label Tr */
            label_tr: string;
            /**
             * Missing Ids
             * @default []
             */
            missing_ids: string[];
            /** Selector */
            selector: components["schemas"]["GroupSelector"] | components["schemas"]["CellTypeSelector"] | components["schemas"]["TransmitterSelector"] | components["schemas"]["NeuropilSelector"] | components["schemas"]["IdsSelector"];
        };
        /**
         * SimulationMode
         * @enum {string}
         */
        SimulationMode: "precomputed" | "live";
        /** StimulateRequest */
        StimulateRequest: {
            /** Components */
            components: components["schemas"]["StimulusRequestItem"][];
        };
        /** StimulateResponse */
        StimulateResponse: {
            brain: components["schemas"]["BrainActivity"];
            output: components["schemas"]["DecoderOutput"];
        };
        /** StimulusComponent */
        StimulusComponent: {
            /** Group */
            group: string;
            /** Intensity */
            intensity?: number | null;
            /** Name Tr */
            name_tr: string;
            /** Neuron Count */
            neuron_count: number;
            /** Rate Hz */
            rate_hz: number;
        };
        /** StimulusGroupInfo */
        StimulusGroupInfo: {
            /** Circuit Only */
            circuit_only: boolean;
            /** Citations */
            citations: number[];
            /** Description Tr */
            description_tr: string;
            /** Key */
            key: string;
            /** Name Tr */
            name_tr: string;
            /** Neuron Count */
            neuron_count: number;
        };
        /** StimulusInfo */
        StimulusInfo: {
            /** Components */
            components: components["schemas"]["StimulusComponent"][];
            /** Match Score */
            match_score?: number | null;
            /** Scenario Key */
            scenario_key: string;
        };
        /** StimulusRequestItem */
        StimulusRequestItem: {
            /** Group */
            group: string;
            /** Intensity */
            intensity: number;
        };
        /** TransmitterSelector */
        TransmitterSelector: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "neurotransmitter";
            /** Neurotransmitter */
            neurotransmitter: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_lab_examples_api_lab_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleInfo"][];
                };
            };
        };
    };
    get_lab_example_api_lab_examples__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lab_job_api_lab_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lab_options_api_lab_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOptions"];
                };
            };
        };
    };
    post_lab_pathways_api_lab_pathways_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathwayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_lab_replay_api_lab_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_lab_report_api_lab_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_lab_run_api_lab_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neuron_search_api_neurons_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellTypeMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neurons_api_neurons__cell_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosResponse"];
                };
            };
        };
    };
    post_stimulate_api_stimulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
